package shared;

/**
 * Generated by Bing AI.
 * 为监听集合变化提供接口。
 * 豆瓣评分 2.0
 * @param <T> 集合元素的类型。
 */
public interface ListListener<T> {
    void beforeAdd(T item);
    void afterAdd(T item);
    void beforeRemove(T item);
    void afterRemove(T item);
    void afterElementPropertyChange(T item);
}
